module VerifyExamples.Eratosthenes.Sieve.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Eratosthenes.Sieve exposing (..)
import Generator as G







spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    wheel2357Init |> sieve\n    |> G.take 10\n    --> [ Prime 2, Prime 3, Prime 5, Prime 7, Prime 11, Prime 13, Prime 17, Prime 19, Prime 23, Prime 29 ]" <|
        \() ->
            Expect.equal
                (
                wheel2357Init |> sieve
                |> G.take 10
                )
                (
                [ Prime 2, Prime 3, Prime 5, Prime 7, Prime 11, Prime 13, Prime 17, Prime 19, Prime 23, Prime 29 ]
                )